source 'https://rubygems.org'

# Use compatible versions of Sinatra and Sinatra-contrib
gem 'sinatra', '~> 3.2.0'
gem 'sinatra-contrib', '~> 3.2.0'

# Other gems
gem 'thin' # or 'puma' as the web server
gem 'rtesseract'
gem 'dotenv-rails', groups: [:development, :test]
gem 'redcarpet' # for Markdown rendering
gem 'pg'